name: kotlin-service-template2
namespace: ""
cdPipelineName: ""
cdPipelineStageName: ""
dnsWildcard: 59ae6b648ca3437aae3a.westeurope.aksapp.io
framework: java11

database:
  required: false


ingress:
  required: false

image:
  name: kotlin-service-template2
  version: latest